# Generated by Django 4.0.1 on 2022-02-17 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
