# Generated by Django 4.0.1 on 2022-02-05 01:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('tag_name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='tags',
            field=models.ManyToManyField(blank=True, to='research.Tag'),
        ),
    ]
