# Generated by Django 4.0.1 on 2022-02-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_tag_feedback_research_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='description',
            new_name='body',
        ),
    ]
