# Generated by Django 4.0.1 on 2022-02-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_research_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image_banner',
            field=models.ImageField(blank=True, default='default-banner.jpg', null=True, upload_to=''),
        ),
    ]
