# Generated by Django 4.0.1 on 2022-02-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_research_image_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='image_banner',
            new_name='banner_image',
        ),
    ]
