# Generated by Django 4.0.1 on 2022-02-15 23:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_rename_image_banner_research_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
