# Generated by Django 4.0.1 on 2022-02-16 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('research', '0008_remove_research_source_research_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
