# Generated by Django 4.0.1 on 2022-02-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_research_research_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='hashes',
        ),
        migrations.AlterField(
            model_name='research',
            name='research_description',
            field=models.CharField(max_length=256),
        ),
    ]
