# Generated by Django 4.0.1 on 2022-04-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interests'),
        ('research', '0012_rename_research_description_research_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('owner', 'research')},
        ),
    ]
